#!/usr/bin/env bash

# Bind to the external (LAN) IP
BIND="$(getent hosts $HOSTNAME | awk '{print $1}')"

if [ -z "$MASTER" ]
then
	echo "Master not set!"
	s6-svscanctl -t /etc/s6
	exit 1
else
	export next="-join=$MASTER"
fi

exec s6-notifywhenup -d 2 ./runner.sh
